### ISSUE TITLE
upgrade buildings effects stay between seasons

### ISSUE THREAD

**Issue by MildlyWarmToast** [Memori-Studios/CastlesOnClouds-Playtest#108] opened 2024-08-29 20:16 UTC
### Current Behavior

im not sure if this is intended or not but currently if you place one of the buildings that unlock a tier 4 upgrade, you can still purchase the tier 4 upgrade in further seasons even if you do not have the building currently placed.

### Expected Behavior

id imagine you are supposed to have to put one down each season since the map is cleared

### Steps To Reproduce

place a tier 4 building in one season and then just keep upgrading in the next one

### Playtest Version (top left)

v0.0.5

### Seed (copy button top left)

Seed: 111012-3763

### Environment Specs

- OS: windows 11
- GPU: nvidia gtx 1650
- CPU: amd ryzen 7 5800HS
- RAM: 16 gb

### Please Attach Player.Log and saveData.json files here

this happened last night in a deleted save so I dont think those will help
[Player.log](https://github.com/user
[saveData.json](https://github.com/user-attachments/files/16805535/saveData.json)
-attachments/files/16805534/Player.log)

### Anything else?

nah

**Comment by Memori-Studios** [comment] 2024-08-30 12:43
Fixed in 0.0.6, It was intended but doesnt make much sense and is sloppy. Thanks for reporting!

https://store.steampowered.com/news/app/1668620/view/4610084577357037789

**Closed as completed by Memori-Studios** 2024-08-30 12:43 UTC
Labels: bug
