### ISSUE TITLE
Unity Error message when going to the merchant via the pop-up icon

### ISSUE THREAD

**Issue by zombiehunternr1** [Memori-Studios/CastlesOnClouds-Playtest#89] opened 2024-05-05 13:28 UTC
### Current Behavior

When the Merchant arrives and you press his icon to go to him, the Unity error message pops up saying something is broken. Luckily the game still continues without breaking or crashing.
![Merchent Unity error message](https://github.com/Memori-Studios/CastlesOnClouds-Playtest/assets/44666850/ee54e5f9-3763-442f-b1bb-1f19ec9af300)

### Expected Behavior

I expect to go to the merchant without getting this error message, or better yet not having this error at all.

### Steps To Reproduce

Just play a mission, wait for the merchant has arrived icon to show up, press it and the error occurs.

### Playtest Version (center top)

v6.3.0

### Seed (copy button center top)

111012-2477

### Environment Specs

- OS: [eg. Windows 10 64-bit]
- GPU: [eg. Nvidia RTX 3070]
- CPU: [eg. i5-14600KF]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment] 2024-06-24 18:41
unable to reproduce, should be fixed in 7.0.2

**Closed by Memori-Studios** 2024-06-24 18:41 UTC
Labels: bug
